[repository]
name = "intranet-trepi"
managed_by_uv = false
changelog = "CHANGELOG.md"
version = "version.txt"
compose = "docker-compose.yml"

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend]
path = "backend"

[backend.package]
name = "trepi.intranet"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend]
path = "frontend"

[frontend.package]
name = "volto-trepi-intranet"
path = "frontend/packages/volto-trepi-intranet"
changelog = "frontend/packages/volto-trepi-intranet/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-trepi-intranet/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "665a7de36b4e4e978774df28a4a7828a8ec01438"
generated_date = "2025-11-27 12:32:02"
